
// Обезличенный каталог интеграций. В продакшене: GET /api/construct/integrations
// (название, назначение, уровень сложности, цена, ограничения, доступ, коннектор). TZ §3.3.
import type { Integration } from '@/types';

export const INTEGRATIONS: readonly Integration[] = [
  // ---------- Мессенджеры (приём и ответы) ----------
  {
    id: 'messenger-whatsapp',
    title: 'Мессенджер: WhatsApp-канал',
    category: 'communication',
    level: 1,
    setupPrice: 9000,
    monthlyPrice: 1500,
    description: 'Приём и ответы в WhatsApp. Один канал — одна интеграция.',
    limits: ['Бот-токен', 'Ограничение частоты отправки: 50/сутки в базовом уровне'],
    requirements: ['Бот-токен'],
    available: true,
    requiresIndividualEstimate: false,
    readyConnector: true,
  },
  {
    id: 'messenger-basic',
    title: 'Мессенджер: базовый канал',
    category: 'communication',
    level: 1,
    setupPrice: 9000,
    monthlyPrice: 1500,
    description: 'Приём и ответы в одном мессенджере (Telegram и подобные).',
    limits: ['Только текст, без вложений в базовом уровне'],
    requirements: ['Бот-токен'],
    available: true,
    requiresIndividualEstimate: false,
    readyConnector: true,
  },
  {
    id: 'messenger-advanced',
    title: 'Мессенджер: расширенный канал',
    category: 'communication',
    level: 3,
    setupPrice: 24000,
    monthlyPrice: 4000,
    description: 'Каналы: приём, отправка, вложения, сценарии.',
    limits: ['Требуется доступ к API мессенджера'],
    requirements: ['Бот-токен', 'Доступ к API'],
    available: true,
    requiresIndividualEstimate: false,
    readyConnector: true,
  },
  // ---------- Социальные сети ----------
  {
    id: 'social-publish',
    title: 'Публикация в соцсети',
    category: 'publishing',
    level: 2,
    setupPrice: 18000,
    monthlyPrice: 2500,
    description: 'Постинг текстов и изображений, комментарии.',
    limits: ['Страница/аккаунт', 'Опционально: статистика'],
    requirements: ['Страница/аккаунт'],
    available: true,
    requiresIndividualEstimate: false,
    readyConnector: true,
  },
  {
    id: 'social-inbound',
    title: 'Соцсеть: приём обращений',
    category: 'communication',
    level: 2,
    setupPrice: 16000,
    monthlyPrice: 2000,
    description: 'Приём и ответы на комментарии и личные сообщения в соцсети.',
    limits: ['Только один аккаунт на интеграцию'],
    requirements: ['Аккаунт соцсети'],
    available: true,
    requiresIndividualEstimate: false,
    readyConnector: true,
  },
  // ---------- Публичные каналы ----------
  {
    id: 'cms-publish',
    title: 'Публикация на сайте (CMS)',
    category: 'publishing',
    level: 2,
    setupPrice: 16000,
    monthlyPrice: 2000,
    description: 'Автопубликация статей и материалов на вашем сайте.',
    limits: ['CMS-аккаунт', 'Один сайт — одна интеграция'],
    requirements: ['CMS-аккаунт'],
    available: true,
    requiresIndividualEstimate: false,
    readyConnector: true,
  },
  {
    id: 'newsletter-publish',
    title: 'Рассылка (email-канал)',
    category: 'publishing',
    level: 2,
    setupPrice: 15000,
    monthlyPrice: 2000,
    description: 'Генерация и отправка email-рассылок по расписанию.',
    limits: ['Сервис рассылок', 'Лимит на количество адресов в уровне'],
    requirements: ['Сервис рассылок'],
    available: true,
    requiresIndividualEstimate: false,
    readyConnector: true,
  },
  // ---------- Почта ----------
  {
    id: 'email-inbox',
    title: 'Почтовый ящик',
    category: 'email',
    level: 2,
    setupPrice: 15000,
    monthlyPrice: 2000,
    description: 'Разбор входящих и автоответы с ящика.',
    limits: ['Каждый ящик — отдельная интеграция'],
    requirements: ['Учётные данные ящика (имя + пароль/токен)'],
    available: true,
    requiresIndividualEstimate: false,
    readyConnector: true,
  },
  // ---------- Внешние сервисы ----------
  {
    id: 'drive-sync',
    title: 'Синхронизация облачного диска',
    category: 'external',
    level: 2,
    setupPrice: 14000,
    monthlyPrice: 1800,
    description: 'Автозагрузка документов на базу знаний.',
    limits: ['Доступ к диску (токен)'],
    requirements: ['Доступ к диску (токен)'],
    available: true,
    requiresIndividualEstimate: false,
    readyConnector: true,
  },
  {
    id: 'external-crm',
    title: 'Стандартная CRM',
    category: 'external',
    level: 2,
    setupPrice: 20000,
    monthlyPrice: 3000,
    description: 'Готовый коннектор к распространённой CRM.',
    limits: ['API-ключ CRM', 'Один контакт — одна интеграция'],
    requirements: ['API-ключ CRM'],
    available: true,
    requiresIndividualEstimate: false,
    readyConnector: true,
  },
  {
    id: 'calendar-sync',
    title: 'Синхронизация календаря',
    category: 'external',
    level: 2,
    setupPrice: 13000,
    monthlyPrice: 1600,
    description: 'Подтяжка встреч и создание событий по результатам.',
    limits: ['Календарный аккаунт'],
    requirements: ['Календарный аккаунт'],
    available: true,
    requiresIndividualEstimate: false,
    readyConnector: true,
  },
  // ---------- Индивидуальные ----------
  {
    id: 'custom-integration',
    title: 'Индивидуальная интеграция',
    category: 'custom',
    level: 'individual',
    description: 'Нестандартный сервис или CRM, отдельная авторизация.',
    limits: ['Оценка по каждой такой интеграции вручную'],
    available: true,
    requiresIndividualEstimate: true,
    readyConnector: false,
  },
] as const;

export const getIntegrationById = (id: string): Integration | undefined =>
  INTEGRATIONS.find((i) => i.id === id);

/** Группы для карточек каталога (TZ §3.3). */
export const INTEGRATION_GROUPS: { key: Integration['category']; title: string }[] = [
  { key: 'communication', title: 'Мессенджеры и общение' },
  { key: 'publishing', title: 'Соцсети и публикационные каналы' },
  { key: 'email', title: 'Электронная почта' },
  { key: 'external', title: 'Внешние сервисы' },
  { key: 'custom', title: 'Индивидуальные интеграции' },
];
