
// Обезличенный каталог продуктов. В продакшене подгружается с backend
// (GET /api/construct/products), здесь — fallback / demo-данные. TZ §2.
import type { Product } from '@/types';

export const PRODUCTS: readonly Product[] = [
  {
    id: 'edu-assistant',
    type: 'single-agent',
    title: 'Образовательный AI-помощник',
    description: 'Ассистент для курса или школы: методички, задания, ответы на вопросы студентов.',
    capabilities: ['Генерация текстов', 'Работа с базой знаний', 'Ответы на обращения'],
    basePrice: 45000,
    monthlyPrice: 9000,
    agentCount: 1,
    availableFeatures: ['gen-text', 'kb-search', 'responses', 'doc-search', 'inbound-analysis'],
    availableIntegrations: ['messenger-basic', 'email-inbox', 'cms-publish'],
  },
  {
    id: 'methodologist',
    type: 'single-agent',
    title: 'AI-методист',
    description: 'Подготовка учебных материалов, планов и заданий по базе знаний курса.',
    capabilities: ['Планы и задания', 'Контент-план', 'Поиск по документам'],
    basePrice: 39000,
    monthlyPrice: 7500,
    agentCount: 1,
    availableFeatures: ['plans', 'content-plan', 'doc-search', 'kb-search'],
    availableIntegrations: ['email-inbox', 'drive-sync'],
  },
  {
    id: 'content-assistant',
    type: 'single-agent',
    title: 'AI-помощник для контента',
    description: 'Создание текстов и визуальных материалов, публикация в соцсетях и блог.',
    capabilities: ['Генерация текста', 'Изображения', 'Публикация материалов'],
    basePrice: 52000,
    monthlyPrice: 11000,
    agentCount: 1,
    availableFeatures: ['gen-text', 'gen-images', 'publish', 'content-plan', 'comment-reply'],
    availableIntegrations: ['social-publish', 'cms-publish', 'messenger-basic'],
  },
  {
    id: 'smm-assistant',
    type: 'single-agent',
    title: 'AI-SMM-ассистент',
    description: 'Лента, контент-план, работа с комментариями и статистикой аудитории.',
    capabilities: ['Контент-план', 'Публикация', 'Комментарии', 'Статистика'],
    basePrice: 58000,
    monthlyPrice: 12000,
    agentCount: 1,
    availableFeatures: ['content-plan', 'publish', 'comment-reply', 'analytics', 'gen-images'],
    availableIntegrations: ['social-publish', 'messenger-advanced', 'email-inbox'],
  },
  {
    id: 'corp-assistant',
    type: 'multi-agent',
    title: 'Корпоративный помощник (комплект)',
    description: 'Комплект из двух агентов: HR-онбординг и внутренний поиск знаний.',
    capabilities: ['Несколько агентов', 'Общая база компании', 'Поиск по документам'],
    basePrice: 120000,
    monthlyPrice: 22000,
    agentCount: 2,
    availableFeatures: ['kb-search', 'doc-search', 'responses', 'multi-employee', 'gen-text'],
    availableIntegrations: ['messenger-advanced', 'email-inbox', 'external-crm'],
  },
  {
    id: 'docs-agent',
    type: 'single-agent',
    title: 'AI-агент для документов',
    description: 'Разбор, классификация и поиск по входящим документам, подготовка выжимок.',
    capabilities: ['Поиск по документам', 'Классификация', 'Суммаризация'],
    basePrice: 49000,
    monthlyPrice: 9500,
    agentCount: 1,
    availableFeatures: ['doc-search', 'kb-search', 'gen-text', 'responses'],
    availableIntegrations: ['email-inbox', 'drive-sync', 'external-crm'],
  },
  {
    id: 'combo',
    type: 'multi-agent',
    title: 'Комбинированный комплект',
    description: 'Три и более агентов под бизнес-процесс. Применяется пакетный тариф.',
    capabilities: ['Несколько агентов', 'Сквозные сценарии', 'Пакетный тариф'],
    basePrice: 190000,
    monthlyPrice: 38000,
    agentCount: 3,
    availableFeatures: ['multi-employee', 'gen-text', 'kb-search', 'responses', 'publish'],
    availableIntegrations: ['messenger-advanced', 'social-publish', 'external-crm', 'custom-integration'],
  },
  {
    id: 'custom-solution',
    type: 'custom',
    title: 'Индивидуальное решение',
    description: 'Нестандартный сценарий под вашу задачу. Переходит в индивидуальную оценку.',
    capabilities: ['Индивидуальные сценарии'],
    basePrice: 0,
    monthlyPrice: 0,
    agentCount: 0,
    availableFeatures: ['custom-scenario', 'video-gen', 'voice-calls'],
    availableIntegrations: ['custom-integration'],
  },
  {
    id: 'consultation',
    type: 'consultation',
    title: 'Консультация по подбору',
    description: 'Поможем выбрать состав агентов и интеграции под вашу задачу.',
    capabilities: ['Подбор под задачу'],
    basePrice: 0,
    monthlyPrice: 0,
    agentCount: 0,
    availableFeatures: [],
    availableIntegrations: [],
  },
] as const;

export const getProductById = (id: string | null): Product | undefined =>
  PRODUCTS.find((p) => p.id === id);
